// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// Coil_handler //
// ------------ //

#define Coil_handler_wrap_target 0
#define Coil_handler_wrap 13

static const uint16_t Coil_handler_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop                               
    0x20a0, //  1: wait   1 pin, 0                   
    0xe001, //  2: set    pins, 1                    
    0xf840, //  3: set    y, 0            side 1     
    0xa04a, //  4: mov    y, !y                      
    0x4001, //  5: in     pins, 1                    
    0xa026, //  6: mov    x, isr                     
    0x0029, //  7: jmp    !x, 9                      
    0x0085, //  8: jmp    y--, 5                     
    0xf000, //  9: set    pins, 0         side 0     
    0xa0c2, // 10: mov    isr, y                     
    0x8000, // 11: push   noblock                    
    0xc000, // 12: irq    nowait 0                   
    0x000d, // 13: jmp    13                         
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program Coil_handler_program = {
    .instructions = Coil_handler_program_instructions,
    .length = 14,
    .origin = -1,
};

static inline pio_sm_config Coil_handler_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + Coil_handler_wrap_target, offset + Coil_handler_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// ----- //
// Timer //
// ----- //

#define Timer_wrap_target 0
#define Timer_wrap 22

static const uint16_t Timer_program_instructions[] = {
            //     .wrap_target
    0xe040, //  0: set    y, 0                       
    0xa04a, //  1: mov    y, !y                      
    0x02c8, //  2: jmp    pin, 8                 [2] 
    0x0082, //  3: jmp    y--, 2                     
    0xe040, //  4: set    y, 0                       
    0xa04a, //  5: mov    y, !y                      
    0xc001, //  6: irq    nowait 1                   
    0x0002, //  7: jmp    2                          
    0xc002, //  8: irq    nowait 2                   
    0xa0c2, //  9: mov    isr, y                     
    0x8000, // 10: push   noblock                    
    0x4001, // 11: in     pins, 1                    
    0xa026, // 12: mov    x, isr                     
    0x0033, // 13: jmp    !x, 19                     
    0x008b, // 14: jmp    y--, 11                    
    0xe040, // 15: set    y, 0                       
    0xa04a, // 16: mov    y, !y                      
    0xc001, // 17: irq    nowait 1                   
    0x000b, // 18: jmp    11                         
    0xc003, // 19: irq    nowait 3                   
    0xa0c2, // 20: mov    isr, y                     
    0x8000, // 21: push   noblock                    
    0x0002, // 22: jmp    2                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program Timer_program = {
    .instructions = Timer_program_instructions,
    .length = 23,
    .origin = -1,
};

static inline pio_sm_config Timer_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + Timer_wrap_target, offset + Timer_wrap);
    return c;
}



#endif
